### ISSUE TITLE
Error byt what?

### ISSUE THREAD

**Issue by Piefje01** [akamming/Domoticz_VolvoRecharge_Plugin#9]
Try to install it on a Rpi

~/domoticz/plugins/domoticz_lg_thinq_plugin

Traceback (most recent call last):
  File "example.py", line 423, in <module>
    main()
  File "example.py", line 419, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
  File "example.py", line 335, in example
    resp = example_command(client, cmd, args)
  File "example.py", line 283, in example_command
    return func(client, *args)
  File "example.py", line 59, in ls
    thinq1_devices = [dev for dev in client.devices if dev.platform_type == "thinq1"]
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
    self._devices = self.session.get_devices()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 526, in get_devices
    return get_list(self.get("service/application/dashboard"), "item")
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 142, in get_list
    val = obj[key]
TypeError: string indices must be integers

**Comment by akamming** [comment]
I think you are posting an issue in the wrong repo. There is no core.py file in a domoticz LG thing directory in this plugin
